version: '3.7'
services:
  front:
    build: ./frontend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    ports:
      - 3000:3000
      - 80:80  
    depends_on:
      - db      
  web:
    hostname: web      
    build: ./lib_catalog
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    hostname: database       
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django


volumes:
  postgres_data:        
