FROM python:3.8-slim
WORKDIR /code
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
COPY lib_catalog/requirements.txt .
RUN pip install -r requirements.txt
COPY lib_catalog/ .
